### ISSUE TITLE
Help + vignette : some suggestions

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/wrassp#33]
The vignette 'wrassp_intro' should at the beginning list all signal processing functions of wrassp with a one-sentence description. I observed that users have problems to find functions in this package. 
I'd suggest to move the part 'The wrasspOutputInfos object' to the very begin of the vignette and extend it by a list of functions + sentence.

The help pages of the wrassp main signal processing functions must refer to other sources (publications, stable URLs) that document the implemented algorithm. 
E.g. the help of ksvF0() should point to the publication:
Schäfer-Vincent K (1983) Pitch period detection and chaining: method and evaluation. Phonetica 1983, Vol 40, pp. 177-202.

**Comment by raphywink** [comment]
I already put together a list of all the main sig. proc. function in the README.md that is displayed here: https://github.com/IPS-LMU/wrassp. Do you think we should additionally add it to the vignette? We could also add a package man page that you can call with  `?wrassp` that gives you the requested overview. 

I agree with the citations but unfortunately there seems to be no simple mechanism to include them in the roxygen2 documentation. I mean we could just write them in there by hand for example in the Details section:

```
F0 analysis of the signal in <listOfFile> using the K. Schaefer-Vincent periodicity detection algortithm (Schäfer-Vincent K (1983) Pitch period detection and chaining: method and evaluation. Phonetica 1983, Vol 40, pp. 177-202.).
```

Apparently there is a pending pull request to include a designated `@cite` field in future roxygen2 package but that package is currently not allowing new features as it is currently in maintenance mode.

**Comment by raphywink** [comment]
I take back what I just said about the roxygen2 doc. I just added the reference field to the doc: https://github.com/IPS-LMU/wrassp/blob/master/R/ksvF0.R#L35

**Comment by florianschiel** [comment]
In that context: when going over help.start() to the wrassp package, you see the typical function list.
However, some of these link names are not objects in the package, e.g. f0ana, f0_ksv ...
The links behind these point to the help pages of the function name in the second column. Why?

**Comment by raphywink** [comment]
Somehow my original reply got lost.... so here I go again:

The reason for this is that some of the tkassp function names differ from the wrassp function names. We included aliases to these functions in case a legacy EMU user is looking for a specific function.
