### ISSUE TITLE
A way to create a AsspDataObj

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/wrassp#35]
As far as I can tell there is no way to get a vector (or matrix) of signal values into a new AsspDataObj from within R and we are therefore limited in EmuR to the functionality of libassp in terms of signal processing. 

It would be a great help, and a way to open up new possibilities, if the wrassp package had an `as.AsspDataObj.vector` function. Since you can use `addTrack` to add more then one tracks later I am not sure that an `as.AsspDataObj.matrix` functionis strictly needed, but I guess it would not be very hard to add that too once the core conversion into an AsspDataObj is solved.

**Comment by raphywink** [comment]
This is already sort of possible although it is not as elegant as it could be. You can see what you have to do here: https://ips-lmu.github.io/The-EMU-SDMS-Manual/app-chap-wrassp.html#sec:app-chap-wrassp-praatsSigProc You basically have to set a few attributes on a list object and change its S3 class. Here is a simplified version:

````{r}
# create AsspDataObj
ado = list()

attr(ado, "trackFormats") =c("INT16")
attr(ado, "sampleRate") = 200

tmpObj = wrassp::read.AsspDataObj(path)
attr(ado, "origFreq") = 44100
attr(ado, "startTime") = startTime

attr(ado, "endRecord") = as.integer(nrow(fmVals))

class(ado) = "AsspDataObj"

wrassp::AsspFileFormat(ado) <- "SSFF"
wrassp::AsspDataFormat(ado) <- as.integer(2) # == binary

ado = wrassp::addTrack(ado, columnNames[1], fmVals, "INT16")
```

**Comment by raphywink** [comment]
Closing this as I don't see that something like a wrapper function would make this any easier than the example above. One would still have to be able to set all of those values and that would make the function just as complicated as setting the individual attributes.
