### ISSUE TITLE
No non-ASCII characters in filenames on Windows?

### ISSUE THREAD

**Issue by kirbyj** [IPS-LMU/wrassp#36]
We have a .wav file collection that includes filenames with non-ASCII characters such as `002_201_201_bål_long_0`.

On macOS, it's possible to create a new emuDB in the usual fashion and import the files using `import_mediaFiles`. The resulting emuDB can then be loaded elsewhere without problems, including on Windows machines.

If we try to build the DB on Windows, `wrassp` throws the following error when calling `import_mediaFiles`:

```
> import_mediaFiles(dbHandle_swedish,
                   dir = "C:/Users/user001/OneDrive/University of Edinburgh/Swedish/002/", verbose = T)
INFO: Importing  240  media files...
  |========                                        |  17%Error in wrassp::read.AsspDataObj(newMediaFileFullPath, 0, 4000) : 
  Can't open file (C:\Users\user001\OneDrive\University of Edinburgh\Swedish\swedish_emuDB\0000_ses\002_201_201_bÃ¥l_long_0_bndl\002_201_201_bÃ¥l_long_0.wav)
```

As shown by `verbose = TRUE`, it seems to get partway there but then chokes on *bål*.

The filenames show up properly in Windows Explorer, and it's possible to read a filename containing such characters directly into RStudio on Windows (i.e., without `wrassp`):

```
install.packages('tuneR')
library(tuneR)
file1 = readWave('C:\Users\user001\OneDrive\University of Edinburgh\Swedish\002\002_202_202_ball_short_2.wav')
file2 = readWave('C:\Users\user001\OneDrive\University of Edinburgh\Swedish\002\002_201_201_bål_long_3.wav')
```
OneDrive is not the culprit (tried moving files to a different location).

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

other attached packages:
[1] wrassp_0.1.9  tibble_3.0.4  emuR_2.1.1    RSQLite_2.2.2
```

**Comment by raphywink** [comment]
yes this is a know issue of the libassp unfortunately. It has to do with how the libassp (written in C .... and quite a while ago as well unfortunately) creates file handles. Fixing this would mean a deep dive into the inner workings of the libassp. I am sure this is doable but I won't get round to it any time soon(ish). Will leave this issue open as a reminder

**Comment by raphywink** [comment]
(what helps though is that I now actually have a Win. 10 / Ubuntu dual-boot machine at work. So I can actually do some developing/testing under Windows without having to cycle home :-))

**Comment by kirbyj** [comment]
No worries, not a showstopper for us, just wasn't sure if it was a known issue or not!

**Comment by raphywink** [comment]
ok this was bugging me like crazy! I always preach to only use utf-8 and a tool that I am responsible 4 doesn't support it properly under Windows. Think I fixed the issue! Could you maybe test it on the machine you where having issues on:
```
devtools::install_github("IPS-LMU/wrassp")
```
then rerun the emuR code?

**Comment by brisaann** [comment]
I had this issue on my Windows machine.  After using `devtools::install_github("IPS-LMU/wrassp")` all my emuR code runs perfectly-- all filenames containing non-ASCII characters are imported into the emuDB.  Thanks a lot!

**Comment by raphywink** [comment]
Ok perfect... thanks for doing the testing! I'll do a bit more testing on my end and then release a new version of wrassp, hopefully  next week some time...

**Comment by raphywink** [comment]
4got to also fix this issue on read actions. This is now implemented (e.g. `zcrana(listOfFiles = ""bål.wav)` now works on Windows)

**Comment by raphywink** [comment]
also fixed bad encoding on filePath attribute on AsspDataObject. Is in new release (1.0.0 on CRAN now(ish)... might still take a few hours)

**Comment by brisaann** [comment]
Revisiting this issue because I'm having the exact same error as the initial posting on my Windows 10 machine, even with the newest wrassp version (1.0.0).  

When using `import_mediaFiles` to import a list of .wav files, where some contain non-ASCII characters (i.e. SW_012_208_208_då_long_0) , `wrassp` throws the following error....

`> import_mediaFiles(dbHandle_swedish,
                   dir = "C:/User/Swedish/012/", verbose = T)
INFO: Importing  240  media files...
  |========                                        |  17%Error in wrassp::read.AsspDataObj(newMediaFileFullPath, 0, 4000) : 
  Can't open file (C:\Users\user001\OneDrive\University of Edinburgh\Swedish\swedish_emuDB\0000_ses\SW_012_201_201_bÃ¥l_long_0_bndl\SW_012_201_201_bÃ¥l_long_0.wav)`

I'm able to import individual .wav files with these characters directly into RStudio on Windows without using `wrassp`.
